### PR TITLE
Set createError.name via defineProperty

### PR DESCRIPTION
**Pull request by shesek**
Implements https://github.com/Raynos/error/issues/15#issuecomment-386568114

Also, move shared utilities to a separate file.

### CODE REVIEW

**Comment by jimmywarting** [comment]
:+1: 

Can we also take the opportunity to replace `xtend` with `Object.assign`

**Comment by shesek** [comment]
Implemented in 267a8f69c97c1e8be136496ec59c76fb9aa41721. (as part of this PR branch, hope that's ok?)

**Comment by freakyfelt** [comment]
My company's Node projects are getting bit by this problem now as well as we add more and more TypeScript into our codebase. We cannot use `ts-node` and `ts-node-dev` due to the use of xtend for changing the name.

**Comment by Raynos** [comment]
I’ll take a look

**Comment by freakyfelt** [comment]
> I’ll take a look

Thanks! One thing I notice on the tests is that I think the response back from Socket has changed in newer versions of Node (3 tests failed due to string mismatch), otherwise this branch seemed to resolve the issues.

**Comment by Raynos** [comment]
I want to maintain back compat with node 0.10 for legacy reasons.

I've fixed this problem using a different approach and published version 7.1.0

**Comment by Raynos** [comment]
@freakyfelt can you link me an issue for the `ts-node` problem so I can verify if 7.1.0 fixed the issue ?

**Comment by freakyfelt** [comment]
Let me see if I can get a repro commit working. Anecdotally 7.2.0 is working great in the project. Thanks for throwing that up there

**Pull request closed without merging**
